config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

Rails.application.routes.draw do
  resources :projects do
    resources :delivery_list
  end
end

app/models/delivery_list.rb
class DeliveryList < ActiveRecord::Base
  unloadable
end

app/models/delivery_partners.rb
class DeliveryPartners < ActiveRecord::Base
  unloadable
end

app/controllers/delivery_list_controller.rb
class DeliveryListController < ApplicationController
  unloadable

  # メニュー選択時にタブが選択状態となるようにするおまじない
  menu_item :delivery_list

  # プロジェクトメニュー配下にするためのおまじない  (初期処理)
  # authorizeは非ログイン時はログイン画面へ遷移するおまじない
  before_filter :find_project, :authorize

  def index
    # 納品一覧を取得する(本日より先の納品一覧)
    @delivery_list = DeliveryList.where("delivery_date >= ?", Date.today);
    @partners_disp_name = DeliveryPartners.find(:all).map(&:disp_name);
  end

  def new
  end

  def show
  end

  def edit
  end

private
  def find_project
    @project = Project.find(params[:project_id])
  rescue ActiveRecord::RecordNotFound
    render_404
  end
end

app/helpers/delivery_list_helper.rb
module DeliveryListHelper
end

app/views/delivery_list/edit.html.erb
<h2>DeliveryListController#edit</h2>

app/views/delivery_list/index.html.erb
<% if (@delivery_list.blank?)%>
	<p class="nodata"><%= l(:label_no_data)%>
<% else %>
	<!-- 登録された納品日一覧を表示  -->
	<table class="list">
		<thead>
			<th><%=h l(:label_delivery_date)%></th>
			<th><%=h l(:label_project_name)%></th>
			<th><%=h l(:label_delivery_partner)%></th>
			<th><%=h l(:label_delivery_item)%></th>
			<th></th>
		</thead>
		<tbody>
			<% @delivery_list.each do |item| %>
				<tr class="<%= cycle('odd', 'even') %>">
					<td align="center"><%=format_time(item.delivery_date) %></td>
					<td align="center"><%=item.project_name %></td>
					<td align="center"><%=@partners_disp_name[item.partner_id - 1]%></td>
					<td align="center"><%=item.delivery_item %></td>
					<td align="center"><%=link_to l(:label_details), project_delivery_list_path(@project, item), :class => 'icon icon-report'%></td>
				</tr>
			<% end %>
		</tbody>
	</table>
<% end %>

app/views/delivery_list/new.html.erb
<h2>DeliveryListController#new</h2>

app/views/delivery_list/show.html.erb
<h2>DeliveryListController#show</h2>